# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20200630_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
