# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 07:00
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20200716_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6),
        ),
    ]
