# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20200629_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
